# Site settings
title: Emerald | A simple Jekyll blog
description: "A minimal blog template, build with Jekyll."
url: "http://lifehaker.github.io/emerald"
author:
  name: "Jacopo Rabolini"
  email: "hello@jacoporabolini.com"
  url: "http://lifehaker.github.io"

# Build settings
baseurl: http://lifehaker.github.io # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: true
custom_nav_footer: true
reverse: false
